---
- name: Delete users
  hosts: nodes
  vars:
    users: [alice, bob, carol]
  tasks:
  - name: Delete
    user:
      name: "{{ item }}"
      force: yes
      state: absent
    with_items: "{{ users }}"
