---
- name: Install packages
  yum:
    name: "{{ packages }}"
    state: latest
- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ services }} "
- name: Open firewall port
  firewalld:
    service: http
    permanent: yes
    immediate: true
    state: enabled

